### ISSUE TITLE
Firmware Compilation Error

### ISSUE THREAD

**Issue by chrisguikema** [esol-community/rmw_zenoh_pico#1]
Hello,

I am following the "Build Linux target" instructions, and I'm getting the following error:

```
Compiling for host environment: not cleaning path
Building firmware for zenoh platform host

...

In file included from /home/chrisguikema/uros_ws/src/uros/rmw_zenoh_pico/rmw_zenoh_pico/src/zenoh_pico/zenoh_pico_data.c:16:
/home/chrisguikema/uros_ws/src/uros/rmw_zenoh_pico/rmw_zenoh_pico/include/rmw_zenoh_pico/rmw_zenoh_pico.h:56:10: fatal error: zenoh-pico/system/common/platform.h: No such file or directory
   56 | #include <zenoh-pico/system/common/platform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I'm running on an Ubuntu 24.04 host with ROS2 Jazzy installed. 

When running the `ros2 run micro_ros_setup create_firmware_ws.sh zenoh host` command, I see this error:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rosidl_typesupport_microxrcedds_test_msg: Cannot locate rosdep definition for [rmw_microxrcedds]
rmw_zenoh_pico: Cannot locate rosdep definition for [zenohpico]
```

Is there a compilation step I missed?

Thanks!

**Comment by k-yokoyama-esol** [comment]
@chrisguikema 
I appreciate your question. Currently, rmw_zenoh_pico runs version 0.11.0.

We have confirmed that 1.3.1 also works, but we are fixing a bug in micro_ros_setup.
Therefore, we have not been able to announce it officially.
Please wait.

**Comment by chrisguikema** [comment]
I was able to get pico-zenoh working on 0.11.0 after opening this issue. I had to make this change, for anyone else who runs into this problem. https://github.com/esol-community/micro_ros_setup/blob/rmw_zenoh_pico/config/zenoh/host/client_host_packages.repos#L60C1-L63C18

Change from `main` to `0.11.0`

```diff
  uros/rmw_zenoh_pico:
    type: git
    url: https://github.com/esol-community/rmw_zenoh_pico.git
-    version: main
+    version: 0.11.0
```

Thanks for confirming 1.3.1, I'll wait to test that out til there is an official announcement.

**Comment by k-yokoyama-esol** [comment]
@chrisguikema 
Sorry for the delay, but we have already released a version compatible with Zenoh 1.4.0. Please let us know if you have any problems.
https://discourse.openrobotics.org/t/update-rmw-zenoh-pico-for-zenoh-1-4-0/50364
